//! Phase 1 firmware smoke test — runs `roms/rp2350/hello_timer.bin` on
//! the emulator and asserts TIMER0 alarm-fire behaviour.
//!
//! The firmware (generated by `roms/rp2350/gen_hello_timer.py`) boots
//! from SRAM via `Emulator::load_image`, configures TIMER0 + TICKS, then
//! spins in an alarm-fire / W1C / counter-increment loop. This test
//! verifies that the emulator's Phase 1 TIMER + TICKS + RESETS guard
//! wiring drives the firmware's counter forward within a bounded number
//! of cycles — a quick "end-to-end" proof that the Phase 1 peripheral
//! stack is connected to the CPU's execute path.

use rp2350_emu::{Config, Emulator};

const HELLO_TIMER_BIN: &[u8] = include_bytes!("../../../roms/rp2350/hello_timer.bin");

/// Counter cell address programmed by the firmware. Must match
/// `COUNTER_ADDR` in `roms/rp2350/gen_hello_timer.py`.
const COUNTER_ADDR: u32 = 0x2000_3000;

/// SRAM base where the firmware image lands (vector table at offset 0,
/// reset handler at offset 0x40).
const LOAD_BASE: u32 = 0x2000_0000;

/// Prepare an emulator to run the SRAM-loaded hello_timer firmware.
/// `Emulator::reset` reads SP/PC from the ROM vector table, but this
/// firmware's vector table lives in SRAM (bypassing the bootrom) — so
/// we explicitly read the vector table out of SRAM post-reset and seed
/// the cores. Core 1 is halted; Core 0 runs the firmware.
fn prepare_emu() -> Emulator {
    let mut emu = Emulator::new(Config::default());
    emu.load_image(LOAD_BASE, HELLO_TIMER_BIN);
    emu.reset();

    // Read SP and reset vector from SRAM (the firmware's actual vector
    // table — ROM would be all zeros).
    let initial_sp = u32::from_le_bytes([
        HELLO_TIMER_BIN[0],
        HELLO_TIMER_BIN[1],
        HELLO_TIMER_BIN[2],
        HELLO_TIMER_BIN[3],
    ]);
    let reset_vector = u32::from_le_bytes([
        HELLO_TIMER_BIN[4],
        HELLO_TIMER_BIN[5],
        HELLO_TIMER_BIN[6],
        HELLO_TIMER_BIN[7],
    ]);
    {
        let arm = emu.cores.expect_arm_mut();
        for i in 0..2 {
            arm[i].regs.msp = initial_sp;
            arm[i].regs.r[13] = initial_sp;
            arm[i].regs.set_pc(reset_vector & !1);
        }
        // Single-core firmware — halt core 1 so `step()` exits its per-core
        // loop quickly and the firmware drives the counter alone.
        arm[1].halt();
    }
    emu
}

#[test]
fn hello_timer_firmware_increments_counter() {
    let mut emu = prepare_emu();

    // Pre-condition: counter reads 0.
    assert_eq!(emu.peek(COUNTER_ADDR), 0, "counter cell must start at 0");

    // Run enough cycles for at least a few alarm fires. At post-bootrom
    // clk_sys = 150 MHz and TICKS.TIMER0.CYCLES = 12, one µs = 12 sys_clks;
    // the firmware's 1000 µs alarm wait = 12_000 sys_clks. Allow 1M
    // sys_clks — enough for ~80 alarm fires with generous headroom for
    // the setup block + poll-loop overhead.
    emu.run(1_000_000).unwrap();

    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 1,
        "firmware must have incremented counter at least once \
         within 1M sys_clks (got {counter})"
    );
}

#[test]
fn hello_timer_firmware_alarm_fires_multiple_times() {
    // Soak version: run longer and expect the counter to advance past 5,
    // proving the alarm-fire loop keeps re-arming.
    let mut emu = prepare_emu();

    // Run 5M sys_clks → ~400 alarm fires at 12_000 sys_clks/fire. We
    // assert >= 5 to leave huge headroom for any scheduling overhead.
    emu.run(5_000_000).unwrap();

    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 5,
        "firmware must fire alarm ≥5 times in 5M sys_clks (got {counter})"
    );
}
