//! Phase 5 RISC-V developer smoke — runs `roms/rp2350/blinky-riscv.bin`
//! on the Hazard3 emulator and asserts GPIO25 toggles (at least one
//! rising and one falling edge) within a generous cycle budget.
//!
//! The firmware (generated by `roms/rp2350/gen_blinky_riscv.py`) boots
//! from SRAM via `Emulator::load_image`. Hazard3's reset PC is
//! `0x2000_0000` per HLD V6 §4.3 / §8 Q1, so no vector-table fixup is
//! needed — the reset path lands on the first encoded instruction.
//!
//! Not a validation claim — see HLD V6 §6 P5: "Developer smoke; not a
//! validation claim."
//!
//! **Dual-core handling.** RP2350 boots both harts at the same PC. The
//! firmware opens with `csrrs x1, mhartid, x0 + beq x1, x0, +8` so core
//! 1 falls through into a `jal x0, 0` park loop while core 0 runs the
//! blinky. Without this guard, both cores XOR the same mask in lockstep
//! and the edges on `gpio_in` cancel out.

use std::time::{Duration, Instant};

use rp2350_emu::{Arch, Config, Emulator, EmulatorBuilder};

const BLINKY_RISCV_BIN: &[u8] = include_bytes!("../../../roms/rp2350/blinky-riscv.bin");

const LOAD_BASE: u32 = 0x2000_0000;
const LED_PIN: u8 = 25;

fn prepare_emu() -> Emulator {
    let mut emu = EmulatorBuilder::new(Config::default())
        .arch(Arch::RiscV)
        .build()
        .unwrap();
    emu.load_image(LOAD_BASE, BLINKY_RISCV_BIN);
    emu.reset();
    emu
}

#[test]
fn blinky_riscv_toggles_led_pin() {
    let mut emu = prepare_emu();

    // Sanity: GPIO25 starts low (post-reset SIO.GPIO_OUT = 0, OE = 0).
    assert!(
        !emu.gpio_read(LED_PIN),
        "GPIO{LED_PIN} should be low at reset"
    );

    let mut seen_high = false;
    let mut seen_low_after_high = false;

    // Per-step budget: the emulator steps one quantum (64 cycles by
    // default). Setup is ~13 instructions + the first delay countdown
    // of ~2047 iterations before the first toggle. 1M cycles is a
    // fat margin.
    let cycle_budget: u64 = 1_000_000;
    let wall_deadline = Instant::now() + Duration::from_millis(2000);

    while emu.cycles() < cycle_budget {
        emu.step().unwrap();

        let high = emu.gpio_read(LED_PIN);
        if high {
            seen_high = true;
        } else if seen_high {
            seen_low_after_high = true;
        }
        if seen_high && seen_low_after_high {
            break;
        }

        assert!(
            Instant::now() < wall_deadline,
            "blinky-riscv did not toggle GPIO{LED_PIN} within 2s wall time \
             (cycles={})",
            emu.cycles()
        );
    }

    assert!(
        seen_high,
        "blinky-riscv never drove GPIO{LED_PIN} high within {cycle_budget} cycles"
    );
    assert!(
        seen_low_after_high,
        "blinky-riscv drove GPIO{LED_PIN} high but never toggled back low"
    );
}

#[test]
fn blinky_riscv_multiple_toggles() {
    let mut emu = prepare_emu();

    // Stricter check: count rising edges. The firmware toggles every
    // ~2047 delay iterations (each a 2-instruction spin). At ~1 cycle/
    // instruction, one edge per ~4_100 cycles. Only core 0 toggles —
    // core 1 is parked by the mhartid guard — so in 1M cycles the
    // single running core should still easily produce >= 10 rising
    // edges on GPIO25.
    let cycle_budget: u64 = 1_000_000;
    let mut last = false;
    let mut rising_edges = 0u32;

    while emu.cycles() < cycle_budget {
        emu.step().unwrap();
        let cur = emu.gpio_read(LED_PIN);
        if cur && !last {
            rising_edges += 1;
        }
        last = cur;
    }

    assert!(
        rising_edges >= 10,
        "blinky-riscv produced {rising_edges} rising edges on GPIO{LED_PIN} \
         in {cycle_budget} cycles, expected >= 10"
    );
}
