//! Phase 3 firmware smoke test -- runs `roms/rp2350/hello_dma.bin` on
//! the emulator and asserts DMA mem-to-mem transfer completes.
//!
//! The firmware (generated by `roms/rp2350/gen_hello_dma.py`) boots
//! from SRAM via `Emulator::load_image`, seeds 4 source words, programs
//! DMA ch0 for a 4-word DREQ_FORCE mem-to-mem transfer, polls BUSY,
//! then writes a marker to `COUNTER_ADDR`. This test verifies the
//! emulator's Phase 3 DMA wiring drives the firmware to completion.

use mdrp2350::{Config, Emulator};

const HELLO_DMA_BIN: &[u8] = include_bytes!("../../../roms/rp2350/hello_dma.bin");

/// Counter cell address programmed by the firmware. Must match
/// `COUNTER_ADDR` in `roms/rp2350/gen_hello_dma.py`.
const COUNTER_ADDR: u32 = 0x2000_3000;

/// Destination address in SRAM (where DMA deposits the words).
const DST_ADDR: u32 = 0x2000_2000;

/// SRAM base where the firmware image lands.
const LOAD_BASE: u32 = 0x2000_0000;

/// Source data the firmware seeds (must match `gen_hello_dma.py`).
const SRC_DATA: [u32; 4] = [0xCAFE_0001, 0xCAFE_0002, 0xCAFE_0003, 0xCAFE_0004];

/// Prepare an emulator to run the SRAM-loaded hello_dma firmware.
fn prepare_emu() -> Emulator {
    let mut emu = Emulator::new(Config::default());
    emu.load_image(LOAD_BASE, HELLO_DMA_BIN);
    emu.reset();

    // Read SP and reset vector from SRAM.
    let initial_sp = u32::from_le_bytes([
        HELLO_DMA_BIN[0], HELLO_DMA_BIN[1],
        HELLO_DMA_BIN[2], HELLO_DMA_BIN[3],
    ]);
    let reset_vector = u32::from_le_bytes([
        HELLO_DMA_BIN[4], HELLO_DMA_BIN[5],
        HELLO_DMA_BIN[6], HELLO_DMA_BIN[7],
    ]);
    {
        let arm = emu.cores.expect_arm_mut();
        for i in 0..2 {
            arm[i].regs.msp = initial_sp;
            arm[i].regs.r[13] = initial_sp;
            arm[i].regs.set_pc(reset_vector & !1);
        }
        // Single-core firmware -- halt core 1.
        arm[1].halt();
    }
    emu
}

#[test]
fn hello_dma_firmware_completes_transfer() {
    let mut emu = prepare_emu();

    // Pre-condition: counter reads 0.
    assert_eq!(emu.peek(COUNTER_ADDR), 0, "counter cell must start at 0");

    // Run enough cycles for the firmware to program DMA, transfer 4
    // words, poll BUSY, and write the marker. The firmware is ~50
    // instructions; 100k cycles is generous headroom.
    emu.run(100_000).unwrap();

    let counter = emu.peek(COUNTER_ADDR);
    assert_eq!(
        counter, 1,
        "firmware must write marker 1 to counter cell after DMA completes (got {counter})"
    );

    // Verify the 4 destination words match the source data.
    for (i, &expected) in SRC_DATA.iter().enumerate() {
        let actual = emu.peek(DST_ADDR + (i as u32) * 4);
        assert_eq!(
            actual, expected,
            "destination word {i} mismatch: expected 0x{expected:08X}, got 0x{actual:08X}"
        );
    }
}
