//! Phase 2 firmware smoke test — runs `roms/rp2350/hello_uart.bin` on
//! the emulator and asserts UART0 TX drain + counter increment.
//!
//! The firmware (generated by `roms/rp2350/gen_hello_uart.py`) boots
//! from SRAM via `Emulator::load_image`, configures UART0 (FEN, UARTEN,
//! TXE), then spins in a TX / wait-for-TXFE / counter-increment loop.
//! This test verifies the emulator's Phase 2 UART drain path drives
//! the firmware's counter forward within a bounded number of cycles.

use mdrp2350::{Config, Emulator};

const HELLO_UART_BIN: &[u8] = include_bytes!("../../../roms/rp2350/hello_uart.bin");

const COUNTER_ADDR: u32 = 0x2000_3000;
const LOAD_BASE: u32 = 0x2000_0000;

fn prepare_emu() -> Emulator {
    let mut emu = Emulator::new(Config::default());
    emu.load_image(LOAD_BASE, HELLO_UART_BIN);
    emu.reset();

    let initial_sp = u32::from_le_bytes([
        HELLO_UART_BIN[0], HELLO_UART_BIN[1],
        HELLO_UART_BIN[2], HELLO_UART_BIN[3],
    ]);
    let reset_vector = u32::from_le_bytes([
        HELLO_UART_BIN[4], HELLO_UART_BIN[5],
        HELLO_UART_BIN[6], HELLO_UART_BIN[7],
    ]);
    for i in 0..2 {
        emu.cores[i].regs.msp = initial_sp;
        emu.cores[i].regs.r[13] = initial_sp;
        emu.cores[i].regs.set_pc(reset_vector & !1);
    }
    emu.cores[1].halt();
    emu
}

#[test]
fn hello_uart_firmware_increments_counter() {
    let mut emu = prepare_emu();
    assert_eq!(emu.peek(COUNTER_ADDR), 0);

    // With IBRD=FBRD=0 the emulator's sysclks-per-byte falls back to 1,
    // so the TX FIFO drains on the first tick. One loop iteration =
    // byte-write + 1-instruction-poll + counter-increment = ~10
    // instructions = ~10-20 sys_clks. 500k cycles gives ≥1000 loop
    // iterations of headroom.
    emu.run(500_000);

    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 1,
        "hello_uart must increment counter at least once in 500k sys_clks (got {counter})"
    );
}

#[test]
fn hello_uart_firmware_loops_many_times() {
    let mut emu = prepare_emu();
    emu.run(2_000_000);
    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 10,
        "hello_uart must loop ≥10 times in 2M sys_clks (got {counter})"
    );
}
