//! Phase 2 firmware smoke test — runs `roms/rp2350/hello_pwm.bin` on
//! the emulator and asserts PWM slice 0 wraps fire.
//!
//! The firmware (generated by `roms/rp2350/gen_hello_pwm.py`) boots
//! from SRAM via `Emulator::load_image`, configures PWM slice 0 with
//! TOP=100, enables it globally, then spins in a poll-INTR / W1C /
//! counter-increment loop. This test verifies the emulator's Phase 2
//! PWM tick + wrap latch drives the firmware counter forward.

use mdrp2350::{Config, Emulator};

const HELLO_PWM_BIN: &[u8] = include_bytes!("../../../roms/rp2350/hello_pwm.bin");

const COUNTER_ADDR: u32 = 0x2000_3000;
const LOAD_BASE: u32 = 0x2000_0000;

fn prepare_emu() -> Emulator {
    let mut emu = Emulator::new(Config::default());
    emu.load_image(LOAD_BASE, HELLO_PWM_BIN);
    emu.reset();

    let initial_sp = u32::from_le_bytes([
        HELLO_PWM_BIN[0], HELLO_PWM_BIN[1],
        HELLO_PWM_BIN[2], HELLO_PWM_BIN[3],
    ]);
    let reset_vector = u32::from_le_bytes([
        HELLO_PWM_BIN[4], HELLO_PWM_BIN[5],
        HELLO_PWM_BIN[6], HELLO_PWM_BIN[7],
    ]);
    for i in 0..2 {
        emu.cores[i].regs.msp = initial_sp;
        emu.cores[i].regs.r[13] = initial_sp;
        emu.cores[i].regs.set_pc(reset_vector & !1);
    }
    emu.cores[1].halt();
    emu
}

#[test]
fn hello_pwm_firmware_increments_counter() {
    let mut emu = prepare_emu();
    assert_eq!(emu.peek(COUNTER_ADDR), 0);

    // Slice 0 wraps every 101 sys_clks at TOP=100. The poll loop is
    // ~5 instructions. After enable, the first wrap should latch
    // within ~200 sys_clks. 100_000 sys_clks gives ~1000 wraps of
    // headroom.
    emu.run(100_000);

    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 1,
        "hello_pwm must increment counter at least once in 100k sys_clks (got {counter})"
    );
}

#[test]
fn hello_pwm_firmware_multiple_wraps() {
    let mut emu = prepare_emu();
    emu.run(1_000_000);
    let counter = emu.peek(COUNTER_ADDR);
    assert!(
        counter >= 10,
        "hello_pwm must wrap ≥10 times in 1M sys_clks (got {counter})"
    );
}
